In [94]:
import textract

text = textract.process('Microsoft/2015 EEO-1.txt')

l = text.split()

print l

['\xef\xbb\xbf6', '0', '104', '4', '0', '22', '0', '1', '15', '1', '0', '2', '0', '0', '155', '275', '97', '5031', '143', '11', '1773', '25', '53', '1388', '58', '3', '403', '6', '13', '9279', '1813', '547', '20502', '972', '72', '11337', '189', '464', '5457', '408', '37', '3723', '54', '167', '45742', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '262', '162', '1799', '284', '11', '222', '13', '35', '818', '180', '6', '109', '4', '26', '3931', '0', '25', '27', '2', '0', '5', '1', '0', '507', '35', '8', '54', '10', '15', '689', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '2356', '831', '27463', '1405', '94', '13359', '228', '553', '8185', '682', '54', '4291', '74', '221', '59796', '2247', '788', '28375', '1411', '93', '13280', '222', '514', '8643', '687', '58', '4374', '73', '196', '60961']

In [95]:
l[0] = '6'

print l

['6', '0', '104', '4', '0', '22', '0', '1', '15', '1', '0', '2', '0', '0', '155', '275', '97', '5031', '143', '11', '1773', '25', '53', '1388', '58', '3', '403', '6', '13', '9279', '1813', '547', '20502', '972', '72', '11337', '189', '464', '5457', '408', '37', '3723', '54', '167', '45742', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '262', '162', '1799', '284', '11', '222', '13', '35', '818', '180', '6', '109', '4', '26', '3931', '0', '25', '27', '2', '0', '5', '1', '0', '507', '35', '8', '54', '10', '15', '689', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '2356', '831', '27463', '1405', '94', '13359', '228', '553', '8185', '682', '54', '4291', '74', '221', '59796', '2247', '788', '28375', '1411', '93', '13280', '222', '514', '8643', '687', '58', '4374', '73', '196', '60961']

In [96]:
nums = [int(n) for n in l]

print nums

[6, 0, 104, 4, 0, 22, 0, 1, 15, 1, 0, 2, 0, 0, 155, 275, 97, 5031, 143, 11, 1773, 25, 53, 1388, 58, 3, 403, 6, 13, 9279, 1813, 547, 20502, 972, 72, 11337, 189, 464, 5457, 408, 37, 3723, 54, 167, 45742, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 262, 162, 1799, 284, 11, 222, 13, 35, 818, 180, 6, 109, 4, 26, 3931, 0, 25, 27, 2, 0, 5, 1, 0, 507, 35, 8, 54, 10, 15, 689, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2356, 831, 27463, 1405, 94, 13359, 228, 553, 8185, 682, 54, 4291, 74, 221, 59796, 2247, 788, 28375, 1411, 93, 13280, 222, 514, 8643, 687, 58, 4374, 73, 196, 60961]

In [97]:
import csv


        
def write(w,d):
    w.writerow([d['year'],d['company'],d['category'],d['ethn'],d['gender'],d['count']])
    

def write_gender(w,d,gender,l,start):
    d['gender'] = gender
    i = start
    ethns = ['White','Black','Pacific Islander','Asian', 'American Indian','Two or More Races']
    for i in range(0,len(ethns)):
        d['ethn'] = ethns[i]
        d['count'] = l[start + i]
        write(w,d)

def write_hispanic(w,d,l,pos):
    d['ethn'] = 'Hispanic'
    d['count'] = l[pos+0]
    d['gender'] = 'Male'
    write(w,d)
    d['gender'] = 'Female'
    d['count'] = l[pos+1]
    write(w,d)



    

def write_category(w,d,l,pos):
    write_hispanic(w,d,l,pos)
    write_gender(w,d,'Male',l,pos+2)
    write_gender(w,d,'Female',l,pos+8)
    
def gen_csv(l,filename,year,company):
    header = ['Year','Company','Category','Ethnicity','Gender','Count']
    with open(filename,"wb") as csvfile:
        w = csv.writer(csvfile)
        w.writerow(header)
        max_ = len(l)
        i = 0
        d = {'year':year,
            'company': company,
            'category':'Executive/Sr. Officials/Mgrs' }
        write_category(w,d,l,i)
        i+=15
        d['category'] = 'First/Mid Managers'
        write_category(w,d,l,i)
        i+=15
        d['category'] = 'Professionals'
        write_category(w,d,l,i)
        i+=15
        d['category'] = 'Technicians'
        write_category(w,d,l,i)
        i+=15
        d['category'] = 'Sales Workers'
        write_category(w,d,l,i)
        i+=15
        d['category'] = 'Admin Support'
        write_category(w,d,l,i)
        i+=15
        d['category'] = 'Craft Workers'
        write_category(w,d,l,i)
        i+=15
        d['category'] = 'Operatives'
        write_category(w,d,l,i)
        i+=15
        d['category'] = 'Laborers & Helpers'
        write_category(w,d,l,i)
        i+=15
        d['category'] = 'Service Workers'
        write_category(w,d,l,i)
        i+=15

In [98]:
gen_csv(l,"Microsoft/eeo1-2015.csv",'2015',"Microsoft")

In [99]:
text = textract.process('LinkedIn/eeo1-2013.txt')

l = text.split()

print l

['2', '2', '89', '2', '0', '25', '0', '4', '30', '0', '0', '13', '0', '0', '167', '7', '10', '149', '1', '0', '95', '0', '8', '80', '2', '0', '48', '1', '6', '407', '43', '26', '632', '17', '9', '620', '1', '32', '327', '13', '2', '314', '1', '9', '2046', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '12', '12', '263', '9', '0', '17', '0', '9', '187', '4', '0', '27', '0', '6', '546', '8', '12', '32', '7', '0', '4', '0', '3', '70', '4', '0', '9', '0', '4', '153', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '72', '62', '1165', '36', '9', '761', '1', '56', '694', '23', '2', '411', '2', '25', '3319', '43', '41', '717', '20', '4', '553', '1', '38', '393', '17', '2', '284', '0', '10', '2123', '0']

In [100]:
gen_csv(l,"LinkedIn/eeo1-2013.csv",'2013','LinkedIn')

In [101]:
text = textract.process('LinkedIn/eeo1-2014.txt')

l = text.split()

print l

['6', '2', '89', '2', '0', '44', '0', '4', '39', '0', '0', '13', '0', '1', '200', '11', '14', '191', '5', '0', '124', '0', '13', '113', '4', '1', '65', '0', '4', '545', '64', '41', '699', '33', '7', '909', '2', '28', '388', '14', '2', '471', '3', '14', '2675', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '9', '16', '280', '13', '0', '24', '0', '6', '243', '6', '0', '34', '0', '8', '639', '6', '13', '41', '5', '0', '4', '0', '2', '83', '9', '0', '11', '0', '2', '176', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '96', '86', '1300', '58', '7', '1105', '2', '53', '866', '33', '3', '594', '3', '29', '4325', '72', '62', '1165', '36', '9', '761', '1', '56', '694', '23', '2', '411', '2', '25', '3319']

In [102]:
gen_csv(l,"LinkedIn/eeo1-2014.csv",'2014','LinkedIn')

In [103]:
text = textract.process('Intel/intel-eeo-report-2014.txt')

l = text.split()

print l

['\xef\xbb\xbf5', '1', '122', '5', '1', '25', '1', '0', '22', '1', '0', '8', '0', '0', '191', '338', '86', '3654', '127', '1', '1259', '15', '38', '998', '36', '4', '335', '4', '8', '6903', '1588', '569', '13717', '715', '23', '9457', '79', '238', '3591', '284', '9', '3923', '34', '1141', '34341', '1214', '246', '4994', '536', '24', '900', '87', '115', '689', '69', '8', '320', '28', '15', '9245', '65', '28', '876', '35', '3', '103', '1', '12', '244', '13', '0', '48', '3', '4', '1435', '18', '163', '68', '9', '0', '12', '0', '1', '695', '43', '0', '78', '5', '16', '1108', '80', '6', '331', '16', '0', '22', '10', '7', '18', '0', '0', '1', '2', '0', '493', 'O', '1', '7', '0', '0', '0', '0', '0', '6', '1', '0', '0', '0', '0', '15', 'O', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '1', 'O', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '3308', '1100', '23769', '1443', '52', '11779', '193', '411', '6263', '447', '21', '4713', '76', '157', '53732', '3513', '1258', '25480', '1557', '62', '12045', '229', '399', '6943', '515', '25', '4757', '83', '160', '57026']

In [104]:
l[0] = '5'
print l

['5', '1', '122', '5', '1', '25', '1', '0', '22', '1', '0', '8', '0', '0', '191', '338', '86', '3654', '127', '1', '1259', '15', '38', '998', '36', '4', '335', '4', '8', '6903', '1588', '569', '13717', '715', '23', '9457', '79', '238', '3591', '284', '9', '3923', '34', '1141', '34341', '1214', '246', '4994', '536', '24', '900', '87', '115', '689', '69', '8', '320', '28', '15', '9245', '65', '28', '876', '35', '3', '103', '1', '12', '244', '13', '0', '48', '3', '4', '1435', '18', '163', '68', '9', '0', '12', '0', '1', '695', '43', '0', '78', '5', '16', '1108', '80', '6', '331', '16', '0', '22', '10', '7', '18', '0', '0', '1', '2', '0', '493', 'O', '1', '7', '0', '0', '0', '0', '0', '6', '1', '0', '0', '0', '0', '15', 'O', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '1', 'O', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '3308', '1100', '23769', '1443', '52', '11779', '193', '411', '6263', '447', '21', '4713', '76', '157', '53732', '3513', '1258', '25480', '1557', '62', '12045', '229', '399', '6943', '515', '25', '4757', '83', '160', '57026']

In [105]:
gen_csv(l,"Intel/eeo1-2014.csv",'2014','Intel')

In [106]:
text = textract.process('Intel/eeo1-2015.txt')

l = text.split()

print l

['1', '0', '65', '2', '0', '8', '1', '0', '9', '1', '0', '1', '0', '0', '88', '347', '99', '357', '133', '4', '1332', '33', '26', '1050', '49', '5', '391', '6', '13', '7015', '1696', '611', '13415', '744', '21', '9913', '79', '248', '3570', '316', '8', '4317', '40', '118', '35096', '1149', '236', '4725', '505', '24', '839', '85', '127', '613', '54', '9', '306', '26', '18', '8716', '53', '25', '810', '39', '1', '109', '1', '5', '233', '12', '0', '48', '2', '2', '1340', '13', '156', '46', '10', '0', '8', '0', '1', '643', '39', '2', '82', '6', '12', '1018', '76', '4', '298', '19', '0', '21', '9', '7', '19', '3', '0', '1', '2', '0', '459', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '3335', '1131', '22886', '1453', '50', '12230', '208', '414', '6137', '474', '24', '5146', '82', '163', '53733', '3308', '1100', '23769', '1443', '52', '11779', '193', '411', '6263', '447', '21', '4713', '76', '157', '53732']

In [107]:
gen_csv(l,"Intel/eeo1-2015.csv",'2015','Intel')

In [108]:
text = textract.process('Google/2013-EEO-1-consolidated-report.txt')

l = text.split()

print l

['\xef\xbb\xbf0', '0', '21', '1', '0', '10', '0', '1', '3', '0', '0', '0', '0', '0', '36', '53', '27', '1791', '28', '3', '632', '7', '53', '744', '21', '5', '332', '2', '15', '3713', '369', '141', '8932', '174', '29', '4469', '18', '352', '2205', '115', '18', '1737', '8', '150', '18717', '16', '1', '287', '14', '0', '31', '4', '7', '25', '4', '0', '10', '1', '0', '400', '65', '62', '1005', '36', '1', '251', '3', '49', '1050', '43', '1', '275', '4', '62', '2907', '24', '39', '106', '13', '3', '34', '1', '15', '299', '31', '3', '106', '0', '45', '719', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '18', '2', '0', '1', '0', '0', '38', '1', '1', '3', '0', '2', '67', '528', '270', '12160', '268', '36', '5428', '33', '477', '4364', '215', '28', '2463', '15', '274', '26559', '443', '219', '10086', '188', '30', '4415', '35', '352', '3745', '176', '28', '2077', '13', '200', '22007']

In [109]:
l[0]='0'

print l

['0', '0', '21', '1', '0', '10', '0', '1', '3', '0', '0', '0', '0', '0', '36', '53', '27', '1791', '28', '3', '632', '7', '53', '744', '21', '5', '332', '2', '15', '3713', '369', '141', '8932', '174', '29', '4469', '18', '352', '2205', '115', '18', '1737', '8', '150', '18717', '16', '1', '287', '14', '0', '31', '4', '7', '25', '4', '0', '10', '1', '0', '400', '65', '62', '1005', '36', '1', '251', '3', '49', '1050', '43', '1', '275', '4', '62', '2907', '24', '39', '106', '13', '3', '34', '1', '15', '299', '31', '3', '106', '0', '45', '719', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '18', '2', '0', '1', '0', '0', '38', '1', '1', '3', '0', '2', '67', '528', '270', '12160', '268', '36', '5428', '33', '477', '4364', '215', '28', '2463', '15', '274', '26559', '443', '219', '10086', '188', '30', '4415', '35', '352', '3745', '176', '28', '2077', '13', '200', '22007']

In [110]:
gen_csv(l,"Google/eeo1-2013.csv",'2013','Google')

In [111]:
text = textract.process('Google/2014_certified_eeo-1_reports_12-12-14.txt')

l = text.split()

print l

['\xef\xbb\xbf0', '0', '15', '1', '0', '5', '0', '0', '4', '0', '0', '0', '0', '0', '25', '208', '107', '3150', '70', '10', '1162', '6', '75', '1622', '60', '10', '739', '2', '53', '7274', '681', '221', '10483', '240', '16', '5536', '15', '288', '2296', '129', '12', '2068', '8', '137', '22130', '9', '0', '252', '15', '1', '8', '5', '6', '33', '4', '0', '2', '0', '1', '336', '61', '70', '781', '48', '1', '138', '2', '20', '757', '34', '5', '140', '2', '27', '2086', '17', '49', '78', '2', '1', '27', '0', '3', '293', '23', '3', '96', '1', '25', '618', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '5', '0', '41', '2', '2', '2', '0', '1', '4', '0', '0', '1', '0', '0', '58', '981', '447', '14800', '378', '31', '6878', '28', '393', '5009', '250', '30', '3046', '13', '243', '32527', '528', '270', '12160', '268', '36', '5428', '33', '477', '4364', '215', '28', '2463', '15', '274', '26559']

In [112]:
l[0]='0'

print l

['0', '0', '15', '1', '0', '5', '0', '0', '4', '0', '0', '0', '0', '0', '25', '208', '107', '3150', '70', '10', '1162', '6', '75', '1622', '60', '10', '739', '2', '53', '7274', '681', '221', '10483', '240', '16', '5536', '15', '288', '2296', '129', '12', '2068', '8', '137', '22130', '9', '0', '252', '15', '1', '8', '5', '6', '33', '4', '0', '2', '0', '1', '336', '61', '70', '781', '48', '1', '138', '2', '20', '757', '34', '5', '140', '2', '27', '2086', '17', '49', '78', '2', '1', '27', '0', '3', '293', '23', '3', '96', '1', '25', '618', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '5', '0', '41', '2', '2', '2', '0', '1', '4', '0', '0', '1', '0', '0', '58', '981', '447', '14800', '378', '31', '6878', '28', '393', '5009', '250', '30', '3046', '13', '243', '32527', '528', '270', '12160', '268', '36', '5428', '33', '477', '4364', '215', '28', '2463', '15', '274', '26559']

In [113]:
gen_csv(l,"Google/eeo1-2014.csv",'2014','Google')

In [114]:
text = textract.process('Facebook/facebook-eeo-1-report-2013.txt')

l = text.split()

print l

['\xef\xbb\xbf5', '2', '94', '0', '0', '18', '0', '2', '31', '0', '0', '6', '0', '0', '158', '7', '8', '267', '7', '0', '131', '0', '15', '103', '1', '0', '55', '0', '6', '600', '60', '23', '1255', '19', '6', '849', '2', '57', '381', '8', '4', '278', '1', '24', '2967', '1', '0', '29', '3', '0', '6', '1', '1', '3', '0', '0', '0', '0', '0', '44', '4', '13', '103', '3', '0', '14', '0', '2', '119', '0', '0', '20', '0', '6', '284', '1', '13', '5', '0', '0', '0', '0', '2', '74', '2', '0', '18', '1', '5', '121', '1', '0', '50', '2', '1', '15', '0', '0', '5', '0', '0', '1', '0', '0', '75', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '2', '1', '6', '0', '2', '0', '0', '2', '1', '0', '0', '0', '0', '0', '14', '81', '60', '1809', '34', '9', '1033', '3', '81', '717', '11', '4', '378', '2', '41', '4263', '52', '54', '1303', '28', '5', '685', '3', '58', '528', '10', '3', '266', '3', '34', '3032']

In [115]:
l[0]='5'

print l

['5', '2', '94', '0', '0', '18', '0', '2', '31', '0', '0', '6', '0', '0', '158', '7', '8', '267', '7', '0', '131', '0', '15', '103', '1', '0', '55', '0', '6', '600', '60', '23', '1255', '19', '6', '849', '2', '57', '381', '8', '4', '278', '1', '24', '2967', '1', '0', '29', '3', '0', '6', '1', '1', '3', '0', '0', '0', '0', '0', '44', '4', '13', '103', '3', '0', '14', '0', '2', '119', '0', '0', '20', '0', '6', '284', '1', '13', '5', '0', '0', '0', '0', '2', '74', '2', '0', '18', '1', '5', '121', '1', '0', '50', '2', '1', '15', '0', '0', '5', '0', '0', '1', '0', '0', '75', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '2', '1', '6', '0', '2', '0', '0', '2', '1', '0', '0', '0', '0', '0', '14', '81', '60', '1809', '34', '9', '1033', '3', '81', '717', '11', '4', '378', '2', '41', '4263', '52', '54', '1303', '28', '5', '685', '3', '58', '528', '10', '3', '266', '3', '34', '3032']

In [116]:
gen_csv(l,"Facebook/eeo1-2013.csv",'2013','Facebook')

In [117]:
text = textract.process('Facebook/2014-eeo-report.txt')

l = text.split()

print l

['\xef\xbb\xbf7', '3', '136', '2', '1', '35', '0', '2', '42', '1', '0', '8', '0', '1', '238', '13', '11', '361', '10', '0', '160', '0', '16', '143', '5', '0', '77', '0', '9', '805', '95', '38', '1546', '26', '5', '1121', '3', '86', '479', '15', '3', '394', '1', '36', '3848', '4', '0', '41', '2', '1', '11', '1', '0', '5', '0', '0', '1', '0', '0', '66', '10', '14', '106', '6', '0', '20', '0', '2', '121', '2', '1', '20', '0', '5', '307', '0', '18', '4', '0', '1', '1', '0', '0', '87', '6', '1', '19', '0', '6', '143', '0', '0', '43', '5', '0', '1', '0', '0', '4', '0', '0', '0', '0', '0', '53', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '8', '1', '2', '2', '0', '2', '3', '0', '0', '0', '0', '0', '19', '130', '84', '2245', '52', '10', '1351', '4', '108', '884', '29', '5', '519', '1', '57', '5479', '81', '60', '1809', '34', '9', '1033', '3', '81', '717', '11', '4', '378', '2', '41', '4263']

In [118]:
l[0]='7'

print l

['7', '3', '136', '2', '1', '35', '0', '2', '42', '1', '0', '8', '0', '1', '238', '13', '11', '361', '10', '0', '160', '0', '16', '143', '5', '0', '77', '0', '9', '805', '95', '38', '1546', '26', '5', '1121', '3', '86', '479', '15', '3', '394', '1', '36', '3848', '4', '0', '41', '2', '1', '11', '1', '0', '5', '0', '0', '1', '0', '0', '66', '10', '14', '106', '6', '0', '20', '0', '2', '121', '2', '1', '20', '0', '5', '307', '0', '18', '4', '0', '1', '1', '0', '0', '87', '6', '1', '19', '0', '6', '143', '0', '0', '43', '5', '0', '1', '0', '0', '4', '0', '0', '0', '0', '0', '53', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '8', '1', '2', '2', '0', '2', '3', '0', '0', '0', '0', '0', '19', '130', '84', '2245', '52', '10', '1351', '4', '108', '884', '29', '5', '519', '1', '57', '5479', '81', '60', '1809', '34', '9', '1033', '3', '81', '717', '11', '4', '378', '2', '41', '4263']

In [119]:
gen_csv(l,"Facebook/eeo1-2014.csv",'2014','Facebook')

In [120]:
text = textract.process('Facebook/Facebook_eeo-1_2015.txt')

l = text.split()

print l

['\xef\xbb\xbf9', '3', '192', '5', '1', '59', '1', '3', '57', '3', '0', '20', '0', '1', '354', '22', '17', '515', '13', '1', '249', '0', '26', '197', '3', '1', '98', '1', '14', '1157', '163', '78', '2299', '57', '5', '1784', '4', '110', '746', '33', '7', '754', '6', '47', '6093', '5', '0', '68', '2', '1', '13', '1', '2', '5', '0', '0', '1', '0', '0', '98', '17', '19', '154', '8', '0', '25', '0', '5', '149', '4', '1', '31', '1', '6', '420', '1', '27', '8', '1', '0', '1', '0', '1', '128', '8', '3', '36', '2', '12', '228', '1', '0', '49', '6', '0', '1', '0', '0', '4', '0', '0', '0', '0', '0', '61', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '17', '2', '2', '6', '0', '1', '3', '0', '1', '2', '0', '0', '35', '219', '144', '3302', '94', '10', '2138', '6', '148', '1289', '51', '13', '942', '10', '80', '8446', '130', '84', '2245', '52', '10', '1351', '4', '108', '884', '29', '5', '519', '1', '57', '5479']

In [121]:
l[0]='9'

print l

['9', '3', '192', '5', '1', '59', '1', '3', '57', '3', '0', '20', '0', '1', '354', '22', '17', '515', '13', '1', '249', '0', '26', '197', '3', '1', '98', '1', '14', '1157', '163', '78', '2299', '57', '5', '1784', '4', '110', '746', '33', '7', '754', '6', '47', '6093', '5', '0', '68', '2', '1', '13', '1', '2', '5', '0', '0', '1', '0', '0', '98', '17', '19', '154', '8', '0', '25', '0', '5', '149', '4', '1', '31', '1', '6', '420', '1', '27', '8', '1', '0', '1', '0', '1', '128', '8', '3', '36', '2', '12', '228', '1', '0', '49', '6', '0', '1', '0', '0', '4', '0', '0', '0', '0', '0', '61', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '17', '2', '2', '6', '0', '1', '3', '0', '1', '2', '0', '0', '35', '219', '144', '3302', '94', '10', '2138', '6', '148', '1289', '51', '13', '942', '10', '80', '8446', '130', '84', '2245', '52', '10', '1351', '4', '108', '884', '29', '5', '519', '1', '57', '5479']

In [122]:
gen_csv(l,"Facebook/eeo1-2015.csv",'2015','Facebook')

In [123]:
text = textract.process('Apple/2014-EEO-1-Consolidated-Report.txt')

l = text.split()

print l

['\xef\xbb\xbf1', '0', '60', '0', '0', '7', '0', '0', '12', '2', '0', '1', '0', '0', '83', '305', '107', '2898', '120', '6', '911', '5', '42', '1114', '81', '4', '320', '1', '28', '5942', '518', '280', '6415', '176', '15', '4178', '24', '135', '1855', '80', '9', '1737', '12', '60', '15494', '1322', '342', '7022', '956', '52', '607', '59', '229', '1844', '561', '15', '231', '18', '122', '13380', '1954', '852', '8798', '1516', '107', '830', '52', '275', '3443', '758', '45', '408', '36', '136', '19210', '583', '489', '1740', '253', '16', '207', '10', '68', '1402', '287', '18', '279', '13', '64', '5429', '10', '0', '65', '2', '1', '15', '1', '0', '0', '0', '0', '0', '0', '0', '94', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '59', '65', '41', '13', '5', '18', '1', '1', '15', '4', '1', '10', '1', '3', '237', '4752', '2135', '27039', '3036', '202', '6773', '152', '750', '9685', '1773', '92', '2986', '81', '413', '59869', '4601', '1962', '25021', '2727', '225', '5534', '147', '803', '8971', '1523', '89', '2563', '80', '398', '54644']

In [124]:
l[0]='1'

print l

['1', '0', '60', '0', '0', '7', '0', '0', '12', '2', '0', '1', '0', '0', '83', '305', '107', '2898', '120', '6', '911', '5', '42', '1114', '81', '4', '320', '1', '28', '5942', '518', '280', '6415', '176', '15', '4178', '24', '135', '1855', '80', '9', '1737', '12', '60', '15494', '1322', '342', '7022', '956', '52', '607', '59', '229', '1844', '561', '15', '231', '18', '122', '13380', '1954', '852', '8798', '1516', '107', '830', '52', '275', '3443', '758', '45', '408', '36', '136', '19210', '583', '489', '1740', '253', '16', '207', '10', '68', '1402', '287', '18', '279', '13', '64', '5429', '10', '0', '65', '2', '1', '15', '1', '0', '0', '0', '0', '0', '0', '0', '94', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '59', '65', '41', '13', '5', '18', '1', '1', '15', '4', '1', '10', '1', '3', '237', '4752', '2135', '27039', '3036', '202', '6773', '152', '750', '9685', '1773', '92', '2986', '81', '413', '59869', '4601', '1962', '25021', '2727', '225', '5534', '147', '803', '8971', '1523', '89', '2563', '80', '398', '54644']

In [125]:
gen_csv(l,"Apple/eeo1-2014.csv",'2014','Apple')

In [126]:
text = textract.process('Apple/2015-EEO-1-Consolidated-Report.txt')

l = text.split()

l = l[1:]
print l

['1', '0', '73', '2', '0', '9', '0', '0', '13', '2', '0', '3', '0', '0', '103', '350', '126', '3534', '139', '10', '1189', '7', '51', '1296', '96', '3', '419', '3', '30', '7253', '641', '323', '8041', '225', '25', '5537', '28', '165', '2423', '112', '11', '2203', '13', '80', '19827', '1545', '526', '7887', '1223', '63', '660', '68', '268', '2468', '874', '21', '234', '27', '167', '16031', '2515', '1147', '9536', '1914', '118', '1046', '57', '296', '4029', '1030', '62', '561', '41', '176', '22528', '615', '537', '1916', '301', '23', '265', '12', '64', '1718', '339', '17', '398', '14', '74', '6293', '13', '0', '87', '2', '1', '14', '0', '0', '0', '0', '0', '1', '0', '0', '118', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '94', '87', '61', '15', '3', '31', '1', '2', '20', '10', '2', '13', '0', '2', '341', '5774', '2746', '31135', '3821', '243', '8751', '173', '846', '11967', '2463', '116', '3832', '98', '529', '72494', '4752', '2135', '27039', '3036', '202', '6773', '152', '750', '9685', '1773', '92', '2986', '81', '413', '59869']

In [127]:
gen_csv(l,"Apple/eeo1-2015.csv",'2015','Apple')

In [128]:
text = textract.process('amazon/ConsolidatedEEO-12014.txt')

l = text.split()


print l

['\xef\xbb\xbf1', '1', '83', '0', '0', '6', '0', '0', '16', '1', '0', '1', '0', '1', '110', '226', '59', '3832', '220', '7', '1026', '12', '101', '1023', '70', '2', '241', '43', '6863', '482', '121', '7718', '228', '22', '4968', '19', '301', '2465', '147', '13', '1636', '13', '133', '18266', '42', '6', '489', '62', '1', '67', '4', '22', '74', '6', '0', '11', '1', '3', '788', '11', '8', '342', '18', '0', '26', '0', '15', '183', '9', '0', '22', '0', '7', '641', '81', '143', '1384', '111', '5', '73', '13', '52', '2134', '176', '5', '146', '20', '102', '4445', '38', '1', '465', '35', '3', '17', '5', '12', '18', '2', '0', '2', '0', '1', '599', '303', '95', '1917', '345', '15', '92', '15', '99', '812', '167', '3', '16', '14', '37', '3930', '2874', '2264', '13087', '5085', '93', '1041', '186', '660', '10105', '4702', '74', '669', '169', '512', '41521', '1', '0', '6', '6', '0', '1', '0', '0', '0', '2', '0', '0', '0', '0', '16', '4059', '2698', '29323', '6110', '146', '7317', '254', '1262', '16830', '5282', '97', '2744', '218', '839', '77179', '2436', '1565', '20930', '3690', '86', '5185', '186', '812', '11783', '3121', '52', '1859', '171', '517', '52393']

In [129]:
l[0]='1'

print l

['1', '1', '83', '0', '0', '6', '0', '0', '16', '1', '0', '1', '0', '1', '110', '226', '59', '3832', '220', '7', '1026', '12', '101', '1023', '70', '2', '241', '43', '6863', '482', '121', '7718', '228', '22', '4968', '19', '301', '2465', '147', '13', '1636', '13', '133', '18266', '42', '6', '489', '62', '1', '67', '4', '22', '74', '6', '0', '11', '1', '3', '788', '11', '8', '342', '18', '0', '26', '0', '15', '183', '9', '0', '22', '0', '7', '641', '81', '143', '1384', '111', '5', '73', '13', '52', '2134', '176', '5', '146', '20', '102', '4445', '38', '1', '465', '35', '3', '17', '5', '12', '18', '2', '0', '2', '0', '1', '599', '303', '95', '1917', '345', '15', '92', '15', '99', '812', '167', '3', '16', '14', '37', '3930', '2874', '2264', '13087', '5085', '93', '1041', '186', '660', '10105', '4702', '74', '669', '169', '512', '41521', '1', '0', '6', '6', '0', '1', '0', '0', '0', '2', '0', '0', '0', '0', '16', '4059', '2698', '29323', '6110', '146', '7317', '254', '1262', '16830', '5282', '97', '2744', '218', '839', '77179', '2436', '1565', '20930', '3690', '86', '5185', '186', '812', '11783', '3121', '52', '1859', '171', '517', '52393']

In [130]:
gen_csv(l,"amazon/eeo1-2014.csv",'2014','Amazon')

In [131]:
text = textract.process('amazon/Consolidated_EEO-1_2015.txt')

l = text.split()

l = l[1:]

print l

['1', '0', '82', '0', '0', '4', '0', '0', '17', '0', '0', '2', '0', '1', '107', '328', '86', '5082', '308', '6', '1522', '22', '168', '1410', '125', '3', '328', '1', '85', '9474', '596', '170', '9579', '342', '30', '6522', '28', '387', '3191', '198', '13', '2217', '18', '189', '23480', '92', '9', '839', '102', '8', '120', '7', '49', '108', '10', '0', '18', '2', '7', '1371', '14', '10', '377', '17', '0', '43', '1', '13', '192', '10', '0', '26', '0', '12', '715', '121', '189', '1549', '172', '3', '103', '16', '69', '2261', '275', '12', '220', '20', '126', '5136', '37', '1', '359', '33', '5', '6', '2', '22', '4', '0', '0', '0', '0', '0', '469', '483', '190', '2371', '498', '25', '128', '29', '179', '940', '267', '9', '31', '19', '71', '5240', '6505', '5593', '17323', '9429', '224', '1932', '355', '1423', '13501', '8912', '170', '1224', '279', '1189', '68059', '1', '0', '5', '6', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '13', '8178', '6248', '37566', '10907', '301', '10380', '460', '2310', '21625', '9797', '207', '4066', '339', '1680', '114064', '4059', '2698', '29323', '6110', '146', '7317', '254', '1262', '16830', '5282', '97', '2744', '218', '839', '77179']

In [132]:
gen_csv(l,"amazon/eeo1-2015.csv",'2015','Amazon')

In [136]:
import pandas as pd

df = pd.read_csv('amazon/eeo1-2014.csv')

tmp = pd.read_csv('amazon/eeo1-2015.csv')

df = pd.concat([df,tmp])

df.tail(15)

     Year Company            Category          Ethnicity  Gender  Count
125  2015  Amazon  Laborers & Helpers  Two or More Races  Female   1189
126  2015  Amazon     Service Workers           Hispanic    Male      1
127  2015  Amazon     Service Workers           Hispanic  Female      0
128  2015  Amazon     Service Workers              White    Male      5
129  2015  Amazon     Service Workers              Black    Male      6
130  2015  Amazon     Service Workers   Pacific Islander    Male      0
131  2015  Amazon     Service Workers              Asian    Male      0
132  2015  Amazon     Service Workers    American Indian    Male      0
133  2015  Amazon     Service Workers  Two or More Races    Male      0
134  2015  Amazon     Service Workers              White  Female      1
135  2015  Amazon     Service Workers              Black  Female      0
136  2015  Amazon     Service Workers   Pacific Islander  Female      0
137  2015  Amazon     Service Workers              Asian  Female      0
138  2015  Amazon     Service Workers    American Indian  Female      0
139  2015  Amazon     Service Workers  Two or More Races  Female      0

In [137]:
tmp = pd.read_csv('Apple/eeo1-2014.csv')

df = pd.concat([df,tmp])
tmp = pd.read_csv('Apple/eeo1-2015.csv')

df = pd.concat([df,tmp])

df.tail(10)

     Year Company         Category          Ethnicity  Gender  Count
130  2015   Apple  Service Workers   Pacific Islander    Male      3
131  2015   Apple  Service Workers              Asian    Male     31
132  2015   Apple  Service Workers    American Indian    Male      1
133  2015   Apple  Service Workers  Two or More Races    Male      2
134  2015   Apple  Service Workers              White  Female     20
135  2015   Apple  Service Workers              Black  Female     10
136  2015   Apple  Service Workers   Pacific Islander  Female      2
137  2015   Apple  Service Workers              Asian  Female     13
138  2015   Apple  Service Workers    American Indian  Female      0
139  2015   Apple  Service Workers  Two or More Races  Female      2

In [138]:
tmp = pd.read_csv('Facebook/eeo1-2013.csv')

df = pd.concat([df,tmp])

tmp = pd.read_csv('Facebook/eeo1-2014.csv')

df = pd.concat([df,tmp])

tmp = pd.read_csv('Facebook/eeo1-2015.csv')

df = pd.concat([df,tmp])

df.tail()

     Year   Company         Category          Ethnicity  Gender  Count
135  2015  Facebook  Service Workers              Black  Female      0
136  2015  Facebook  Service Workers   Pacific Islander  Female      1
137  2015  Facebook  Service Workers              Asian  Female      2
138  2015  Facebook  Service Workers    American Indian  Female      0
139  2015  Facebook  Service Workers  Two or More Races  Female      0

In [139]:
tmp = pd.read_csv('Google/eeo1-2013.csv')

df = pd.concat([df,tmp])

tmp = pd.read_csv('Google/eeo1-2014.csv')

df = pd.concat([df,tmp])

In [140]:
tmp = pd.read_csv('Intel/eeo1-2014.csv')

df = pd.concat([df,tmp])

tmp = pd.read_csv('Intel/eeo1-2015.csv')

df = pd.concat([df,tmp])

In [141]:
tmp = pd.read_csv('LinkedIn/eeo1-2013.csv')

df = pd.concat([df,tmp])

tmp = pd.read_csv('LinkedIn/eeo1-2014.csv')

df = pd.concat([df,tmp])

In [142]:
tmp = pd.read_csv('Microsoft/eeo1-2015.csv')

df = pd.concat([df,tmp])

In [143]:
df.to_csv('eeo1-tech.csv')